# Generated by Django 4.0.6 on 2024-05-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stucture',
            new_name='Structure',
        ),
    ]
