# Generated by Django 4.0.6 on 2024-05-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_payer', models.FloatField(default=0.0)),
                ('lieu_paiement', models.CharField(default='', max_length=50)),
                ('en_ordre', models.BooleanField()),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frais.typesfrais')),
                ('etudiant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etudiant')),
            ],
        ),
    ]
