# Generated by Django 4.0.6 on 2024-05-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
        ('frais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='frais',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='frais',
            name='montant_a_payer',
        ),
        migrations.RemoveField(
            model_name='frais',
            name='type_frais',
        ),
        migrations.AlterField(
            model_name='frais',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etudiant'),
        ),
        migrations.AlterField(
            model_name='frais',
            name='registered_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='frais',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frais.typesfrais'),
        ),
    ]
